### ISSUE TITLE
How to run on a RPI4

### ISSUE THREAD

**Issue by Tsjippy** [exquo/signal-libs-build#17]
I try to run signal-cli on a RPI4 with "arm_64bit=0" set in config.txt. I have to set that because other sqlite lib problems.

If I use aarch64-linux-gnu I get `wrong ELF class: ELFCLASS64 (Possible cause: can't load AARCH64 .so on a ARM platform)`

If I use the arm7 lib I get `org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup (AssertionError)`

What can I do?

**Comment by Duke-Jones** [comment]
Hi, Ive built a [script](https://github.com/Duke-Jones/signal_cli_on_raspi) which installs or updates signal-cli on 32 or 64bit versions of a Raspberry 4.
It automatically downloads the required dependencies, compile them if necessary and patches the signal-cli.
Maybe this helps :-)

**Comment by exquo** [comment]
The 
> "arm_64bit=0" in config.txt

is RPi-specific, I'm not sure what its effect is. Perhaps it's effectively a 32-bit system running on 64-bit processor? Can you post the output of

	uname -a
	file /lib/systemd/systemd
	file -L $(type -p java)

Here is the same issue caused by a 32-bit Java on a 64-bit RPi3: https://github.com/AsamK/signal-cli/issues/1088.

As for the 
> other sqlite lib problems.

The readme in https://github.com/Duke-Jones/signal_cli_on_raspi mentions
> on aarch64 systems only: download corresponding sources for libsqlitejdbc.so, compile and patch signal-cli installation with it (https://github.com/xerial/sqlite-jdbc)

which might help with that problem.

P.S. Sorry I have not seen this issue when it was created!
