### ISSUE TITLE
full-fledged builds?

### ISSUE THREAD

**Issue by piramiday** [exquo/signal-libs-build#5]
hello there, thanks for your awesome repo.

do you think it would make sense to go the extra mile and publish full releases with such libraries included?

for example, for ARM64 one has to download your libraries, download the latest signal version, upgrade the libs in the tarfile and then install.
would it be easy for you to publish the whole updated archives?
that would speed up the process for any user to install.

**Comment by exquo** [comment]
Sure thing! Yes, the full releases (i.e. signal-cli bundled with the compiled libraries for the appropriate platform) are already published for `x86_64` Linux, MacOS and Windows. 

Doing the same for all the supported platforms is a bit resource-wasteful, since the bulk of those platform-specific packages is the same for all of them; only the two compiled libraries differ. While storage is cheap (and github's storage does not cost me personally anything :) ), I dislike the idea of filling it with redundant data. 

It might be convenient to have a ready package for one's platform, but "making" one takes only two commands (see [instructions](https://github.com/exquo/signal-libs-build#other-architectures)). People installing signal-cli on Raspberry Pis and such are probably comfortable enough with doing that. 

What I've been considering doing instead though, is to add a script for the users that will automatically download the appropriate files for a particular architecture and patch them into the 'base' version of signal-cli package.

**Comment by piramiday** [comment]
thanks for the reply: I do get your point with respect to being wasteful and I agree.

maybe, as you wrote, a script would suffice?
something similar to the instructions using the `zip` update feature, but with all versions and filenames already filled in?

e.g. is there something better than `curl`ing the latest release page at https://github.com/exquo/signal-libs-build/releases/latest and fetching the necessary files? maybe using some GitHub APIs to directly fetch the assets' URLs?

**Comment by exquo** [comment]
Yes, for the script this is pretty much exactly what I've been thinking - download the releases info (best done using the GitHub API, yes) and the appropriate files, then use `zip` like in the instructions to update the `.jar` files.

**Comment by piramiday** [comment]
yes, but that script requires logic and maintenance on its own:
- regarding logic, that's where the downgrade problem (e.g.) comes in, as it's not straightforward to understand which lib versions each signal-cli version requires;
- regarding maintenance, for obvious reasons.
I had just coded my own script to automatically update my several cross-architecture signal installations based on the releases on your repo, and then the very next day I had to rewrite pretty much all of it given your new design of the Github Actions, releases names, versions, and so on.
not your fault, but rather an unlucky coincidence, but still... quite annoying!
with "full-fledged" releases this would be quite trivial to update.

I also tried to take a look at this repo's forks for repos that had the old organization of packages and thus would work with my older script, but for some reason those failed to produce all the different files, e.g. https://github.com/archeranton/signal-libs-build/releases/tag/v0.9.1 ...
I won't go into the details of a pretty complex YAML file (kudos on making that work BTW), as well.

so, I will close this issue as it's clear full releases do not agree with your publishing stance, and I guess I will hopefully keep maintaining my script for the time being... :smiley:

**Comment by exquo** [comment]
Just to make sure we're talking about the same thing: the "script" I have mentioned will be published as a _part of this repo_. It will work with whatever releases structure this repo has or will have in the future. So its "logic and maintenance" will be _this_ repo's responsibility.

Regarding downgrades / downloading specific versions of signal-cli: it will be an optional argument to the script. By default it will download the latest release.

P.S. Sorry about the timing with writing your script. Once there is a download script in this repo, you should be able to simply use it.

**Comment by piramiday** [comment]
yes, of course. but still, I will always need another script that takes care of installing it for me, putting the executable in the right spot, send a test message to the right number and so on...
